/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAAYcyclic.SystemAdiminClient.view.panel.content;

import CAAYcyclic.SystemAdiminClient.enumeration.ApplicationColor;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Youssef
 */
public class AlertPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlertPanel
     */
    public AlertPanel() {
        initComponents();
    }

    public JLabel getMessageDlg() {
        return messageDlg;
    }

    public JButton getNegativeBtn() {
        return negativeBtn;
    }

    public JButton getPositiveBtn() {
        return positiveBtn;
    }

    public JLabel getTitleDlg() {
        return titleDlg;
    }

    public void setMessageDlg(JLabel messageDlg) {
        this.messageDlg = messageDlg;
    }

    public void setNegativeBtn(JButton negativeBtn) {
        this.negativeBtn = negativeBtn;
    }

    public void setPositiveBtn(JButton positiveBtn) {
        this.positiveBtn = positiveBtn;
    }

    public void setTitleDlg(JLabel titleDlg) {
        this.titleDlg = titleDlg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positiveBtn = new javax.swing.JButton();
        negativeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        messageDlg = new javax.swing.JLabel();
        titleDlg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        positiveBtn.setBackground(ApplicationColor.accentColor.value);
        positiveBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        positiveBtn.setForeground(new java.awt.Color(255, 255, 255));
        positiveBtn.setText("PositiveBtn");
        positiveBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        positiveBtn.setOpaque(true);
        positiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positiveBtnActionPerformed(evt);
            }
        });

        negativeBtn.setBackground(new java.awt.Color(255, 255, 255));
        negativeBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        negativeBtn.setText("NegativeBtn");
        negativeBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        messageDlg.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        messageDlg.setText("message");
        messageDlg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        titleDlg.setBackground(new java.awt.Color(255, 255, 255));
        titleDlg.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titleDlg.setForeground(ApplicationColor.primaryColor.value);
        titleDlg.setText("Alert");
        titleDlg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, ApplicationColor.primaryColor.value));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(negativeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(positiveBtn))
                            .addComponent(titleDlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageDlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(titleDlg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(negativeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(positiveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void positiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positiveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positiveBtnActionPerformed

    public void refresh(){
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel messageDlg;
    private javax.swing.JButton negativeBtn;
    private javax.swing.JButton positiveBtn;
    private javax.swing.JLabel titleDlg;
    // End of variables declaration//GEN-END:variables
}
