/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAAYcyclic.SystemAdiminClient.view.panel.content;

import CAAYcyclic.SystemAdiminClient.enumeration.ApplicationColor;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Youssef
 */
public class ProcedureFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserForm
     */
    public ProcedureFormPanel() {
        initComponents();
    }

    public void refresh() {
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        roundedPanel1 = new CAAYcyclic.SystemAdiminClient.view.panel.component.RoundedPanel();
        panelDescription = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstFild = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        descriptionTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTxt = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        saveBtn = new CAAYcyclic.SystemAdiminClient.view.panel.component.RoundedButton();

        setBackground(new java.awt.Color(242, 241, 241));
        setForeground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(879, 666));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        titleLabel.setForeground(ApplicationColor.primaryColor.value);
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Procedure");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        titleLabel.setIconTextGap(0);
        titleLabel.setMaximumSize(new java.awt.Dimension(200, 46));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setForeground(new java.awt.Color(255, 255, 255));

        panelDescription.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelDescription.setForeground(new java.awt.Color(153, 153, 153));
        panelDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelDescription.setText("Use this form to generate new procedure");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        firstFild.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        firstFild.setForeground(ApplicationColor.primaryColor.value);
        firstFild.setText("Title");

        titleTxt.setForeground(new java.awt.Color(153, 153, 153));
        titleTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        titleTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                titleTxtFocusLost(evt);
            }
        });
        titleTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTxtMouseClicked(evt);
            }
        });

        descriptionTitle.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        descriptionTitle.setForeground(ApplicationColor.primaryColor.value);
        descriptionTitle.setText("Description");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        descriptionTxt.setColumns(20);
        descriptionTxt.setForeground(new java.awt.Color(153, 153, 153));
        descriptionTxt.setRows(5);
        descriptionTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        descriptionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionTxtFocusLost(evt);
            }
        });
        descriptionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTxtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(descriptionTxt);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        saveBtn.setBackground(ApplicationColor.accentColor.value);
        saveBtn.setText("Save");
        saveBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addComponent(jSeparator2)))
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(panelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(154, 154, 154))
                            .addComponent(jScrollPane2)
                            .addComponent(firstFild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descriptionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleTxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(firstFild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionTitle)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 147, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titleTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleTxtFocusLost
        titleTxt.setForeground(Color.decode("#999999"));
        titleTxt.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.decode("#999999")),BorderFactory.createEmptyBorder(5,5,5,5)));
        refresh();
    }//GEN-LAST:event_titleTxtFocusLost

    private void titleTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTxtMouseClicked
        titleTxt.setForeground(ApplicationColor.primaryColor.value);
        titleTxt.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,0,3,0,ApplicationColor.accentColor.value),BorderFactory.createEmptyBorder(5,5,5,5)));
        refresh();
    }//GEN-LAST:event_titleTxtMouseClicked

    private void descriptionTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTxtMouseClicked
        descriptionTxt.setForeground(ApplicationColor.primaryColor.value);
        refresh();
    }//GEN-LAST:event_descriptionTxtMouseClicked

    private void descriptionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTxtFocusLost
        descriptionTxt.setForeground(Color.decode("#999999"));
        refresh();
    }//GEN-LAST:event_descriptionTxtFocusLost

    public JTextArea getDescriptionTxt() {
        return descriptionTxt;
    }

    public JTextField getTitleTxt() {
        return titleTxt;
    }

    public JLabel getDescriptionTitle() {
        return descriptionTitle;
    }

    public JLabel getProcedureTitle() {
        return firstFild;
    }

    public JButton getSaveBtn() {
        return saveBtn;
    }

    public void setTitleInvalid() {
        titleTxt.setForeground(Color.RED);
        titleTxt.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED),BorderFactory.createEmptyBorder(5,5,5,5)));
        refresh();
    }

    public void setSavingText(){
        saveBtn.setText("Saving...");
        refresh();
    }

    public void setSaveText(){
        saveBtn.setText("Save");
        refresh();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JTextArea descriptionTxt;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel firstFild;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel panelDescription;
    private CAAYcyclic.SystemAdiminClient.view.panel.component.RoundedPanel roundedPanel1;
    private CAAYcyclic.SystemAdiminClient.view.panel.component.RoundedButton saveBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
